[project]
name = "fastapi-stackauth"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115",
    "uvicorn>=0.34",
    "python-dotenv>=1.0",
]

[tool.uv.sources]
gl-iam = { path = "/Users/sandy.a.dewangga/Workspace/Gli/gl-sdk/libs/gl-iam" }
