services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/server.key
      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTPS_TRUST_STORE_FILE: /opt/keycloak/conf/certs/ca.crt
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./realm:/opt/keycloak/data/import
      - ./certs:/opt/keycloak/conf/certs:ro
